language: node_js
node_js:
  - lts/*
cache: yarn

before_deploy:
  - yarn bundle
deploy:
  provider: releases
  api_key:
    secure: 1IqaL66fIyJU1sqpBlaGma8VqDP4Jyrdrz3tivDf3tbA6gfON4UOAoj0Gl3kI3r2OPVfxOmniDw0ar7AJHId9rbATt9kBlnmYFGpsnL6kj4UP7Qb57ir02G8DjwrBgNAaLxgqMcljSMV2/MUq/tGcEKGWzn9J973HrZr307iKadvGN5uCzow22Cxua8R0kWBCT8yvvH1bDJLbcmiSU8vdXxo0fQfnFBRLlD/wl0YLWUJixMrI2Z09f4R9Vk+6VYLjKsQ1sBiQWIXNla5QBVl2DTpM1VO3Sp84QGuT4HjwB86xGIABQc5wL02/BeKqKFgA2ObiGwe3tp+S8ldmQ+V87yxJauXd7W5PQvDs+5mv067Na5+nahYXZjfwe9ca48TNEhq1Mjg1e4ymvi+QbD6uDHeAbAQVo6nWxEookaEP7P3DmmLLKqhhb39aGUs3ZLyMJE4O7CfHv92Rh0k4abC1ziUmOuQtkZvjZ7/mOxxNM3nf95MM99J13rWeNIMN6QadDi4B9A4aUWkAQImpr0FjfEY1uwhUgOHrk1dnRFqwhBUUFkxtBt8TbmPyrKDtSB7K6SkRGLQV4iLJScwb+/miKpLG0ph9A4/xucZoXkF/j5UCZkBnFFCmaebm9bT5+AJs4h5KMYVZnETrMDqhsDEa06TVs0fd6k6tgWVBAsbvRQ=
  file: dex-batch-explorer.tar.gz
  on:
    repo: gnosis/dex-batch-explorer
  skip_cleanup: true
  draft: true
